package zemberek7;

import java.util.ArrayList;
import java.util.List;

public class QuestionAnalyzer {

    List<String> questions = new ArrayList<String>();

    QuestionAnalyzer() {
        questions.add("Kaç");
        questions.add("Kaça");
        questions.add("Kaçı");
        questions.add("Kaçta");
        questions.add("Kaçtan");
        questions.add("Kaçıncı");
        questions.add("Kaçıncısı");
        questions.add("Kim");
        questions.add("Kime");
        questions.add("Kimi");
        questions.add("Kimde");
        questions.add("Kimden");
        questions.add("Kimin");
        questions.add("Kiminle");
        questions.add("Kimler");
        questions.add("Kimlere");
        questions.add("Kimleri");
        questions.add("Kimlerde");
        questions.add("Kimlerden");
        questions.add("Kimlerle");
        questions.add("Nasıl");
        questions.add("Ne kadar");
        questions.add("Ne zaman");
        questions.add("Ne");
        questions.add("Neler");
        questions.add("Neleri");
        questions.add("Nelere");
        questions.add("Nelerde");
        questions.add("Nelerden");
        questions.add("Neden");
        questions.add("Nere");
        questions.add("Nerede");
        questions.add("Nereden");
        questions.add("Nereye");
        questions.add("Nereyi");
        questions.add("Neresi");
        questions.add("Neyi");
        questions.add("Neye");
        questions.add("Neyde");
        questions.add("Neyden");
        questions.add("Neyle");
        questions.add("Niçin");
        questions.add("Niye");
        questions.add("Hangi");
        questions.add("Hangisi");
        questions.add("Hangileri");
        questions.add("kaç");
        questions.add("kaça");
        questions.add("kaçı");
        questions.add("kaçta");
        questions.add("kaçtan");
        questions.add("kaçıncı");
        questions.add("kaçıncısı");
        questions.add("kim");
        questions.add("kime");
        questions.add("kimi");
        questions.add("kimde");
        questions.add("kimden");
        questions.add("kimin");
        questions.add("kiminle");
        questions.add("kimler");
        questions.add("kimlere");
        questions.add("kimleri");
        questions.add("kimlerde");
        questions.add("kimlerden");
        questions.add("kimlerle");
        questions.add("nasıl");
        questions.add("ne kadar");
        questions.add("ne zaman");
        questions.add("ne");
        questions.add("neler");
        questions.add("neleri");
        questions.add("nelere");
        questions.add("nelerde");
        questions.add("nelerden");
        questions.add("neden");
        questions.add("nere");
        questions.add("nerede");
        questions.add("nereden");
        questions.add("nereye");
        questions.add("nereyi");
        questions.add("neresi");
        questions.add("neyi");
        questions.add("neye");
        questions.add("neyde");
        questions.add("neyden");
        questions.add("neyle");
        questions.add("niçin");
        questions.add("niye");
        questions.add("hangi");
        questions.add("hangisi");
        questions.add("hangileri");
    }
}
